version: '3.7'

services:
   flask-app:
      container_name: "flask"
      restart: always
      build: ./app/
      command: python app.py run -h 0.0.0.0
      volumes:
         - ./app/:/usr/src/app/
      ports:
         - 80:8000
      environment:
         - DB_HOST=postgres-db
         - DB_USER=myuser
         - DB_PASSWD=mypass
      depends_on:
         - postgres-db

   postgres-db:
      container_name: "postgres"
      restart: always
      image: postgres:10
      volumes:
         - postgres_data:/var/lib/postgresql/data
         - ./resource/create_database.sql:/docker-entrypoint-initdb.d/database.sql
      ports:
         - "5432:5432"
      environment:
         - POSTGRES_USER=myuser
         - POSTGRES_PASSWORD=mypass

volumes:
   postgres_data:
